job:build-jdk-17-deliver:
  image: gradle:7.2.0-jdk17
  stage: build
  script:
    - cd codenames
    - gradle --warning-mode all $PROXY build
  artifacts:
    name: build-$CI_BUILD_REF_SLUG-$CI_COMMIT_SHA
    expire_in: 5 mins 0 sec
    paths:
      - codenames/build/libs/*.war
  only:
    - main
  tags:
    - docker
  allow_failure: false

job:release-gitlab:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release-tag
  script:
    - echo "Running the release job."
  release:
    name: 'Release v0.$CI_PIPELINE_IID'
    tag_name: 'v0.$CI_PIPELINE_IID'
    description: "Create a release using the release-cli."
    ref: $CI_COMMIT_SHA
  only:
    - main
  tags:
    - docker
  allow_failure: false
